apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        timeout: 2h0m0s
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/pullrequest.yaml@versionStream
            name: ""
            resources:
              requests: {}
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - name: jx-variables
            - name: build-make-linux
              resources: {}
            - name: build-make-test
              resources: {}
            - name: build-container-build
              resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 2h0m0s
status: {}
